-- +goose Up
CREATE TYPE chair_type AS ENUM ('abc', 'cde');

CREATE TABLE main (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    title TEXT NOT NULL,
    sub_id BIGINT NOT NULL CHECK (sub_id > 0),
    sub_obj TEXT NOT NULL CHECK (sub_obj IN ('tools', 'tables', 'chairs')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    main_id BIGINT NOT NULL UNIQUE REFERENCES main (id),
    description1 TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    main_id BIGINT NOT NULL UNIQUE REFERENCES main (id),
    description2 TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE chairs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    main_id BIGINT NOT NULL UNIQUE REFERENCES main (id),
    description3 TEXT,
    type chair_type NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

-- Ordered active reads avoid scanning the soft-deleted portion of Main.
CREATE INDEX main_active_id_idx ON main (id) WHERE deleted_at IS NULL;

-- +goose Down
DROP TABLE chairs;
DROP TABLE tables;
DROP TABLE tools;
DROP TABLE main;
DROP TYPE chair_type;
