// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/EgorKo25/main-satellite-graphql-api/internal/domain"
)

type MainCreateInput struct {
	Title     string         `json:"title"`
	Satellite map[string]any `json:"satellite"`
}

type MainDeleteInput struct {
	ID int64 `json:"id"`
}

type MainMutationInput struct {
	Create graphql.Omittable[*MainCreateInput] `json:"create,omitempty"`
	Update graphql.Omittable[*MainUpdateInput] `json:"update,omitempty"`
	Delete graphql.Omittable[*MainDeleteInput] `json:"delete,omitempty"`
}

type MainMutationPayload struct {
	Main      *domain.Main `json:"main,omitempty"`
	DeletedID *int64       `json:"deletedId,omitempty"`
}

type MainUpdateInput struct {
	ID        int64                             `json:"id"`
	Title     graphql.Omittable[*string]        `json:"title,omitempty"`
	Satellite graphql.Omittable[map[string]any] `json:"satellite,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
