// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Satellite interface {
	IsSatellite()
}

type Chair struct {
	ID           string     `json:"id"`
	Description3 *string    `json:"description3,omitempty"`
	Type         ChairType  `json:"type"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt,omitempty"`
}

func (Chair) IsSatellite() {}

type ChairCreateInput struct {
	Description3 graphql.Omittable[*string] `json:"description3,omitempty"`
	Type         ChairType                  `json:"type"`
}

type ChairUpdateInput struct {
	Description3 graphql.Omittable[*string]    `json:"description3,omitempty"`
	Type         graphql.Omittable[*ChairType] `json:"type,omitempty"`
}

type Main struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Satellite Satellite  `json:"satellite"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type MainCreateInput struct {
	Title     string                `json:"title"`
	Satellite *SatelliteCreateInput `json:"satellite"`
}

type MainDeleteInput struct {
	ID string `json:"id"`
}

type MainMutationInput struct {
	Create graphql.Omittable[*MainCreateInput] `json:"create,omitempty"`
	Update graphql.Omittable[*MainUpdateInput] `json:"update,omitempty"`
	Delete graphql.Omittable[*MainDeleteInput] `json:"delete,omitempty"`
}

type MainMutationPayload struct {
	Main      *Main   `json:"main,omitempty"`
	DeletedID *string `json:"deletedId,omitempty"`
}

type MainUpdateInput struct {
	ID        string                                   `json:"id"`
	Title     graphql.Omittable[*string]               `json:"title,omitempty"`
	Satellite graphql.Omittable[*SatelliteUpdateInput] `json:"satellite,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SatelliteCreateInput struct {
	Tool  graphql.Omittable[*ToolCreateInput]  `json:"tool,omitempty"`
	Table graphql.Omittable[*TableCreateInput] `json:"table,omitempty"`
	Chair graphql.Omittable[*ChairCreateInput] `json:"chair,omitempty"`
}

type SatelliteUpdateInput struct {
	Tool  graphql.Omittable[*ToolUpdateInput]  `json:"tool,omitempty"`
	Table graphql.Omittable[*TableUpdateInput] `json:"table,omitempty"`
	Chair graphql.Omittable[*ChairUpdateInput] `json:"chair,omitempty"`
}

type Table struct {
	ID           string     `json:"id"`
	Description2 *string    `json:"description2,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt,omitempty"`
}

func (Table) IsSatellite() {}

type TableCreateInput struct {
	Description2 graphql.Omittable[*string] `json:"description2,omitempty"`
}

type TableUpdateInput struct {
	Description2 graphql.Omittable[*string] `json:"description2,omitempty"`
}

type Tool struct {
	ID           string     `json:"id"`
	Description1 *string    `json:"description1,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt,omitempty"`
}

func (Tool) IsSatellite() {}

type ToolCreateInput struct {
	Description1 graphql.Omittable[*string] `json:"description1,omitempty"`
}

type ToolUpdateInput struct {
	Description1 graphql.Omittable[*string] `json:"description1,omitempty"`
}

type ChairType string

const (
	ChairTypeAbc ChairType = "abc"
	ChairTypeCde ChairType = "cde"
)

var AllChairType = []ChairType{
	ChairTypeAbc,
	ChairTypeCde,
}

func (e ChairType) IsValid() bool {
	switch e {
	case ChairTypeAbc, ChairTypeCde:
		return true
	}
	return false
}

func (e ChairType) String() string {
	return string(e)
}

func (e *ChairType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChairType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChairType", str)
	}
	return nil
}

func (e ChairType) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChairType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChairType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
