// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/EgorKo25/main-satellite-graphql-api/internal/domain"
	"github.com/EgorKo25/main-satellite-graphql-api/internal/postgres"
)

type MainCreateInput struct {
	Title     string                `json:"title"`
	Satellite *SatelliteCreateInput `json:"satellite"`
}

type MainDeleteInput struct {
	ID int64 `json:"id"`
}

type MainMutationInput struct {
	Create graphql.Omittable[*MainCreateInput] `json:"create,omitempty"`
	Update graphql.Omittable[*MainUpdateInput] `json:"update,omitempty"`
	Delete graphql.Omittable[*MainDeleteInput] `json:"delete,omitempty"`
}

type MainMutationPayload struct {
	Main      *domain.Main `json:"main,omitempty"`
	DeletedID *int64       `json:"deletedId,omitempty"`
}

type MainUpdateInput struct {
	ID        int64                                    `json:"id"`
	Title     graphql.Omittable[*string]               `json:"title,omitempty"`
	Satellite graphql.Omittable[*SatelliteUpdateInput] `json:"satellite,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SatelliteCreateInput struct {
	Tool  graphql.Omittable[*postgres.ToolCreate]  `json:"tool,omitempty"`
	Table graphql.Omittable[*postgres.TableCreate] `json:"table,omitempty"`
	Chair graphql.Omittable[*postgres.ChairCreate] `json:"chair,omitempty"`
}

type SatelliteUpdateInput struct {
	Tool  graphql.Omittable[*postgres.ToolUpdate]  `json:"tool,omitempty"`
	Table graphql.Omittable[*postgres.TableUpdate] `json:"table,omitempty"`
	Chair graphql.Omittable[*postgres.ChairUpdate] `json:"chair,omitempty"`
}
