// Code generated by MockGen. DO NOT EDIT.
// Source: resolver.go
//
// Generated by this command:
//
//	mockgen -source=resolver.go -destination=database_mock_test.go -package=graph -mock_names=mainDatabase=MockMainDatabase
//

// Package graph is a generated GoMock package.
package graph

import (
	context "context"
	reflect "reflect"

	graphql "github.com/99designs/gqlgen/graphql"
	domain "github.com/EgorKo25/main-satellite-graphql-api/internal/domain"
	postgres "github.com/EgorKo25/main-satellite-graphql-api/internal/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockMainDatabase is a mock of mainDatabase interface.
type MockMainDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockMainDatabaseMockRecorder
	isgomock struct{}
}

// MockMainDatabaseMockRecorder is the mock recorder for MockMainDatabase.
type MockMainDatabaseMockRecorder struct {
	mock *MockMainDatabase
}

// NewMockMainDatabase creates a new mock instance.
func NewMockMainDatabase(ctrl *gomock.Controller) *MockMainDatabase {
	mock := &MockMainDatabase{ctrl: ctrl}
	mock.recorder = &MockMainDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMainDatabase) EXPECT() *MockMainDatabaseMockRecorder {
	return m.recorder
}

// CreateChair mocks base method.
func (m *MockMainDatabase) CreateChair(arg0 context.Context, arg1 string, arg2 postgres.ChairCreate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChair", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChair indicates an expected call of CreateChair.
func (mr *MockMainDatabaseMockRecorder) CreateChair(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChair", reflect.TypeOf((*MockMainDatabase)(nil).CreateChair), arg0, arg1, arg2)
}

// CreateTable mocks base method.
func (m *MockMainDatabase) CreateTable(arg0 context.Context, arg1 string, arg2 postgres.TableCreate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockMainDatabaseMockRecorder) CreateTable(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockMainDatabase)(nil).CreateTable), arg0, arg1, arg2)
}

// CreateTool mocks base method.
func (m *MockMainDatabase) CreateTool(arg0 context.Context, arg1 string, arg2 postgres.ToolCreate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTool", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTool indicates an expected call of CreateTool.
func (mr *MockMainDatabaseMockRecorder) CreateTool(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTool", reflect.TypeOf((*MockMainDatabase)(nil).CreateTool), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockMainDatabase) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMainDatabaseMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMainDatabase)(nil).Delete), arg0, arg1)
}

// List mocks base method.
func (m *MockMainDatabase) List(arg0 context.Context, arg1 postgres.ListInput) ([]*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMainDatabaseMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMainDatabase)(nil).List), arg0, arg1)
}

// UpdateChair mocks base method.
func (m *MockMainDatabase) UpdateChair(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string], arg3 postgres.ChairUpdate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChair", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChair indicates an expected call of UpdateChair.
func (mr *MockMainDatabaseMockRecorder) UpdateChair(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChair", reflect.TypeOf((*MockMainDatabase)(nil).UpdateChair), arg0, arg1, arg2, arg3)
}

// UpdateMain mocks base method.
func (m *MockMainDatabase) UpdateMain(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string]) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMain", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMain indicates an expected call of UpdateMain.
func (mr *MockMainDatabaseMockRecorder) UpdateMain(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMain", reflect.TypeOf((*MockMainDatabase)(nil).UpdateMain), arg0, arg1, arg2)
}

// UpdateTable mocks base method.
func (m *MockMainDatabase) UpdateTable(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string], arg3 postgres.TableUpdate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTable", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockMainDatabaseMockRecorder) UpdateTable(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockMainDatabase)(nil).UpdateTable), arg0, arg1, arg2, arg3)
}

// UpdateTool mocks base method.
func (m *MockMainDatabase) UpdateTool(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string], arg3 postgres.ToolUpdate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTool", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTool indicates an expected call of UpdateTool.
func (mr *MockMainDatabaseMockRecorder) UpdateTool(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTool", reflect.TypeOf((*MockMainDatabase)(nil).UpdateTool), arg0, arg1, arg2, arg3)
}
