// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/EgorKo25/main-satellite-graphql-api/internal/graph (interfaces: mainReader)
//
// Generated by this command:
//
//	mockgen -destination=reader_mock_test.go -package=graph -mock_names=mainReader=MockMainReader . mainReader
//

// Package graph is a generated GoMock package.
package graph

import (
	context "context"
	reflect "reflect"

	domain "github.com/EgorKo25/main-satellite-graphql-api/internal/domain"
	postgres "github.com/EgorKo25/main-satellite-graphql-api/internal/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockMainReader is a mock of mainReader interface.
type MockMainReader struct {
	ctrl     *gomock.Controller
	recorder *MockMainReaderMockRecorder
	isgomock struct{}
}

// MockMainReaderMockRecorder is the mock recorder for MockMainReader.
type MockMainReaderMockRecorder struct {
	mock *MockMainReader
}

// NewMockMainReader creates a new mock instance.
func NewMockMainReader(ctrl *gomock.Controller) *MockMainReader {
	mock := &MockMainReader{ctrl: ctrl}
	mock.recorder = &MockMainReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMainReader) EXPECT() *MockMainReaderMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockMainReader) List(arg0 context.Context, arg1 postgres.ListInput) ([]*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMainReaderMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMainReader)(nil).List), arg0, arg1)
}
