package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"strconv"

	"github.com/EgorKo25/main-satellite-graphql-api/internal/domain"
	"github.com/EgorKo25/main-satellite-graphql-api/internal/graph/generated"
	"github.com/EgorKo25/main-satellite-graphql-api/internal/graph/model"
)

// Main is the resolver for the main field.
func (r *mutationResolver) Main(ctx context.Context, input model.MainMutationInput) (*model.MainMutationPayload, error) {
	if err := oneOf(presence(input.Create), presence(input.Update), presence(input.Delete)); err != nil {
		return nil, err
	}
	switch {
	case input.Create.IsSet():
		mapped, err := createInput(*input.Create.Value())
		if err != nil {
			return nil, err
		}
		value, err := r.service.Create(ctx, mapped)
		if err != nil {
			return nil, serviceError(err)
		}
		return &model.MainMutationPayload{Main: outputMain(value)}, nil
	case input.Update.IsSet():
		mapped, err := updateInput(*input.Update.Value())
		if err != nil {
			return nil, err
		}
		value, err := r.service.Update(ctx, mapped)
		if err != nil {
			return nil, serviceError(err)
		}
		return &model.MainMutationPayload{Main: outputMain(value)}, nil
	default:
		id, err := domain.ParseID(input.Delete.Value().ID)
		if err != nil {
			return nil, err
		}
		deleted, err := r.service.Delete(ctx, id)
		if err != nil {
			return nil, serviceError(err)
		}
		output := strconv.FormatInt(deleted, 10)
		return &model.MainMutationPayload{DeletedID: &output}, nil
	}
}

// Main is the resolver for the main field.
func (r *queryResolver) Main(ctx context.Context, id *string, limit int32, offset int32) ([]*model.Main, error) {
	input := domain.ListInput{Limit: int(limit), Offset: int(offset)}
	if id != nil {
		parsed, err := domain.ParseID(*id)
		if err != nil {
			return nil, err
		}
		input.ID = &parsed
	}
	values, err := r.service.List(ctx, input)
	if err != nil {
		return nil, serviceError(err)
	}
	output := make([]*model.Main, 0, len(values))
	for _, value := range values {
		output = append(output, outputMain(value))
	}
	return output, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
