// Code generated by MockGen. DO NOT EDIT.
// Source: resolver.go
//
// Generated by this command:
//
//	mockgen -source=resolver.go -destination=service_mock_test.go -package=graph -mock_names=mainService=MockMainService
//

// Package graph is a generated GoMock package.
package graph

import (
	context "context"
	reflect "reflect"

	domain "github.com/EgorKo25/main-satellite-graphql-api/internal/domain"
	service "github.com/EgorKo25/main-satellite-graphql-api/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockMainService is a mock of mainService interface.
type MockMainService struct {
	ctrl     *gomock.Controller
	recorder *MockMainServiceMockRecorder
	isgomock struct{}
}

// MockMainServiceMockRecorder is the mock recorder for MockMainService.
type MockMainServiceMockRecorder struct {
	mock *MockMainService
}

// NewMockMainService creates a new mock instance.
func NewMockMainService(ctrl *gomock.Controller) *MockMainService {
	mock := &MockMainService{ctrl: ctrl}
	mock.recorder = &MockMainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMainService) EXPECT() *MockMainServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMainService) Create(arg0 context.Context, arg1 service.CreateInput) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMainServiceMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMainService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockMainService) Delete(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockMainServiceMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMainService)(nil).Delete), arg0, arg1)
}

// List mocks base method.
func (m *MockMainService) List(arg0 context.Context, arg1 service.ListInput) ([]*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMainServiceMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMainService)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockMainService) Update(arg0 context.Context, arg1 service.UpdateInput) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMainServiceMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMainService)(nil).Update), arg0, arg1)
}
