// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/EgorKo25/main-satellite-graphql-api/internal/graph (interfaces: mainWriter)
//
// Generated by this command:
//
//	mockgen -destination=writer_mock_test.go -package=graph -mock_names=mainWriter=MockMainWriter . mainWriter
//

// Package graph is a generated GoMock package.
package graph

import (
	context "context"
	reflect "reflect"

	graphql "github.com/99designs/gqlgen/graphql"
	domain "github.com/EgorKo25/main-satellite-graphql-api/internal/domain"
	postgres "github.com/EgorKo25/main-satellite-graphql-api/internal/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockMainWriter is a mock of mainWriter interface.
type MockMainWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMainWriterMockRecorder
	isgomock struct{}
}

// MockMainWriterMockRecorder is the mock recorder for MockMainWriter.
type MockMainWriterMockRecorder struct {
	mock *MockMainWriter
}

// NewMockMainWriter creates a new mock instance.
func NewMockMainWriter(ctrl *gomock.Controller) *MockMainWriter {
	mock := &MockMainWriter{ctrl: ctrl}
	mock.recorder = &MockMainWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMainWriter) EXPECT() *MockMainWriterMockRecorder {
	return m.recorder
}

// CreateChair mocks base method.
func (m *MockMainWriter) CreateChair(arg0 context.Context, arg1 string, arg2 postgres.ChairCreate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChair", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChair indicates an expected call of CreateChair.
func (mr *MockMainWriterMockRecorder) CreateChair(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChair", reflect.TypeOf((*MockMainWriter)(nil).CreateChair), arg0, arg1, arg2)
}

// CreateTable mocks base method.
func (m *MockMainWriter) CreateTable(arg0 context.Context, arg1 string, arg2 postgres.TableCreate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockMainWriterMockRecorder) CreateTable(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockMainWriter)(nil).CreateTable), arg0, arg1, arg2)
}

// CreateTool mocks base method.
func (m *MockMainWriter) CreateTool(arg0 context.Context, arg1 string, arg2 postgres.ToolCreate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTool", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTool indicates an expected call of CreateTool.
func (mr *MockMainWriterMockRecorder) CreateTool(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTool", reflect.TypeOf((*MockMainWriter)(nil).CreateTool), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockMainWriter) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMainWriterMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMainWriter)(nil).Delete), arg0, arg1)
}

// UpdateChair mocks base method.
func (m *MockMainWriter) UpdateChair(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string], arg3 postgres.ChairUpdate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChair", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChair indicates an expected call of UpdateChair.
func (mr *MockMainWriterMockRecorder) UpdateChair(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChair", reflect.TypeOf((*MockMainWriter)(nil).UpdateChair), arg0, arg1, arg2, arg3)
}

// UpdateMain mocks base method.
func (m *MockMainWriter) UpdateMain(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string]) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMain", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMain indicates an expected call of UpdateMain.
func (mr *MockMainWriterMockRecorder) UpdateMain(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMain", reflect.TypeOf((*MockMainWriter)(nil).UpdateMain), arg0, arg1, arg2)
}

// UpdateTable mocks base method.
func (m *MockMainWriter) UpdateTable(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string], arg3 postgres.TableUpdate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTable", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockMainWriterMockRecorder) UpdateTable(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockMainWriter)(nil).UpdateTable), arg0, arg1, arg2, arg3)
}

// UpdateTool mocks base method.
func (m *MockMainWriter) UpdateTool(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string], arg3 postgres.ToolUpdate) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTool", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTool indicates an expected call of UpdateTool.
func (mr *MockMainWriterMockRecorder) UpdateTool(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTool", reflect.TypeOf((*MockMainWriter)(nil).UpdateTool), arg0, arg1, arg2, arg3)
}
