// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/EgorKo25/main-satellite-graphql-api/internal/graph (interfaces: mainWriter)
//
// Generated by this command:
//
//	mockgen -destination=writer_mock_test.go -package=graph -mock_names=mainWriter=MockMainWriter . mainWriter
//

// Package graph is a generated GoMock package.
package graph

import (
	context "context"
	reflect "reflect"

	graphql "github.com/99designs/gqlgen/graphql"
	domain "github.com/EgorKo25/main-satellite-graphql-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMainWriter is a mock of mainWriter interface.
type MockMainWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMainWriterMockRecorder
	isgomock struct{}
}

// MockMainWriterMockRecorder is the mock recorder for MockMainWriter.
type MockMainWriterMockRecorder struct {
	mock *MockMainWriter
}

// NewMockMainWriter creates a new mock instance.
func NewMockMainWriter(ctrl *gomock.Controller) *MockMainWriter {
	mock := &MockMainWriter{ctrl: ctrl}
	mock.recorder = &MockMainWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMainWriter) EXPECT() *MockMainWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMainWriter) Create(arg0 context.Context, arg1 string, arg2 map[string]any) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMainWriterMockRecorder) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMainWriter)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockMainWriter) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMainWriterMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMainWriter)(nil).Delete), arg0, arg1)
}

// Update mocks base method.
func (m *MockMainWriter) Update(arg0 context.Context, arg1 int64, arg2 graphql.Omittable[*string], arg3 graphql.Omittable[map[string]any]) (*domain.Main, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Main)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMainWriterMockRecorder) Update(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMainWriter)(nil).Update), arg0, arg1, arg2, arg3)
}
